export const SET_AMOUNT="SET_AMOUNT";
export const SET_LAST_AMOUNT="SET_LAST_AMOUNT";
export const SET_OPERATION="SET_OPERATION";
export const SET_BEFORE="SET_BEFORE";
export const SET_LAST_WAS_OPERATION="SET_LAST_WAS_OPERATION";

export const AUTH_START="AUTH_START";
export const AUTH_SUCCESS="AUTH_SUCCESS";
export const AUTH_FAIL="AUTH_FAIL";
export const AUTH_LOGOUT="AUTH_LOGOUT";

export const SAVE_RES_START="SAVE_RES_START";
export const SAVE_RES_SUCCESS="SAVE_RES_SUCCESS";
export const SAVE_RES_FAIL="SAVE_RES_FAIL";

export const FETCH_RES_START="FETCH_RES_START";
export const FETCH_RES_SUCCESS="FETCH_RES_SUCCESS";
export const FETCH_RES_FAILED="FETCH_RES_FAILED";

export const SET_AUTH_REDIRECT_PATH="SET_AUTH_REDIRECT_PATH";
export const ABOUT_TO_SAVE="ABOUT_TO_SAVE";




