export const SET_AMOUNT="SET_AMOUNT";
export const SET_LAST_AMOUNT="SET_LAST_AMOUNT";
export const SET_OPERATION="SET_OPERATION";
export const SET_BEFORE="SET_BEFORE";
export const SET_LAST_WAS_OPERATION="SET_LAST_WAS_OPERATION";

export const AUTH_START="AUTH_START";
export const AUTH_SUCCESS="AUTH_SUCCESS";
export const AUTH_FAIL="AUTH_FAIL";
export const AUTH_INITIATE_LOGOUT="AUTH_INITIATE_LOGOUT";
export const AUTH_LOGOUT="AUTH_LOGOUT";
export const AUTH_CHECK_TIMEOUT="AUTH_CHECK_TIMEOUT";
export const AUTH_USER="AUTH_USER";
export const AUTH_CHECK_STATE="AUTH_CHECK_STATE";

export const SAVE_RES_START="SAVE_RES_START";
export const SAVE_RES_SUCCESS="SAVE_RES_SUCCESS";
export const SAVE_RES_FAIL="SAVE_RES_FAIL";
export const SAVE_RES_INITIALIZE="SAVE_RES_INITIALIZE";

export const FETCH_RES_START="FETCH_RES_START";
export const FETCH_RES_SUCCESS="FETCH_RES_SUCCESS";
export const FETCH_RES_FAILED="FETCH_RES_FAILED";
export const FETCH_RES_INITIALIZE="FETCH_RES_INITIALIZE";

export const HIDE_CHANGE="HIDE_CHANGE";

export const FETCH_SINGLE_RES_START="FETCH_SINGLE_RES_START";
export const FETCH_SINGLE_RES_SUCCESS="FETCH_SINGLE_RES_SUCCESS";
export const FETCH_SINGLE_RES_FAILED="FETCH_SINGLE_RES_FAILED";
export const FETCH_SINGLE_RES_INITIALIZE="FETCH_SINGLE_RES_INITIALIZE";

export const SET_AUTH_REDIRECT_PATH="SET_AUTH_REDIRECT_PATH";
export const ABOUT_TO_SAVE="ABOUT_TO_SAVE";




